### ISSUE TITLE
suggestion: use scattering for cities generation

### ISSUE THREAD

**Issue by jeancallisti** [Gameslinx/Tessellation#114]
Dear mod authors,
Your mod is amazing and is adding a lot of immersion to all planets. Only Kerbin receives very little love.

But I was thinking about another use for the mod, with a little bit of extra effort: how about generating cities on Kerbin? Instead of rock meshes, have a handful of house or building meshes -- or road meshes, but I think that last one would be harder.

It doesn't matter if the cities makes sense. Just having big chunks of random buildings here and there would suffice.

The benefit would be extraordinary: no one really wants to build planes in the game because 1) there's nothing to see on Kerbin, and 2) they're almost immediately superceded (in terms of exploration and science) by rockets.
Now they would have a reason to be used!

Last but not least, being able to crash into houses would be a good incentive too ;-) Totally in the spirit of Kerbals!

**Comment by Gameslinx** [comment]
Hey, thanks for the suggestion. Sadly, the scatter system is entirely random. Placing buildings in organised blocks as seen in most cities isn't possible without them clipping into each other. Individual houses are possible, but it isn't a good use of resources because they are not very frequently occurring. Might as well use the default, existing scatter system for that

**Comment by jeancallisti** [comment]
You could still have a "farm" mesh, with one small house in the middle, surrounded by a flat field with a texture. It wouldn't matter if fields overlap or if they're properly aligned.
Again: only an idea.
