### ISSUE TITLE
Circular area showing parallax then white square around

### ISSUE THREAD

**Issue by Massetstephane** [Gameslinx/Tessellation#40]
hi ! i have a problem: 
- KSC it's ok
![KSC ok](https://i.imgur.com/P9GROkY.png)
- In flight close to the ship
![flight](https://i.imgur.com/gfmsb7Q.png)
- View in the distance
![far](https://i.imgur.com/khZMJXI.png)
> Parallax operates on a circular area close to the ship and beyond that there is this white texture.
I play in 4k with an RTX3090, and 64 giga memory (DDR3600).
windows10, KSP 1.11.1 (patch french), last GeForce Experience Nvidia drivers: 461.72
Parallax  1.2.1, KopernicusBE_19+_Release80
And for now I have no visual environment mod, just parallax.
[KSP.log](https://github.com/Gameslinx/Tessellation/files/6053809/KSP.log)

**Comment by Gameslinx** [comment]
Can you try using the stable Kopernicus version (not bleeding edge)?

**Comment by Massetstephane** [comment]
hi ! 
yes tested both , @Spaceman.Spiff  my advised to do it on the forum (ksp).

and it's the same problem !

**Comment by victormakeaveli** [comment]
Every planet with atmosphere had this weird white looking thing around and I decided to find whats causing it since I don't have any graphical mod so..

I solved it by removing the highlighted mods:

![Screenshot_20210306_152226](https://user-images.githubusercontent.com/55029810/110216859-456b9180-7e90-11eb-8873-2e959fc2043f.jpg)

It took me like idk.. MANY hours testing Parallax with every single mod I have starting KSP and quitting right after , I'm pretty sure i lost about 5% of my ssd's health doing that.

I hope I could help you.

https://imgur.com/gallery/K1J9VTj

**Comment by Massetstephane** [comment]
hi !
@victormakeaveli  , These mods are not installed in my GameData folder !!
So the problem is elsewhere in my current configuration.
My GameData folder.
![image](https://user-images.githubusercontent.com/70191880/110236076-24f51300-7f34-11eb-862d-ed7fcdf333bd.png)
steph.

**Comment by victormakeaveli** [comment]
@Massetstephane I'd recommend you do the same as I did: testing.
First make a cross list of mods we have in common, then add like 3 of yours per game launch, and keep it untill you find whats causing the issue.

Since we have some in common that will save you some work (:

**Comment by Massetstephane** [comment]
hi !
Ok right now I'm working on an IVA mod but I'll test KSP only with Parallax I'd quickly fix it as well. See you soon.

**Comment by victormakeaveli** [comment]
ohhh i never thought about, kos with some iva must be hella cool

**Comment by Massetstephane** [comment]
Hi ! problem resolved
As I explained on the KSP forum, it was one of my icons (agency) that I had renamed in .truecolor, not knowing at all why there is this format or how to convert an image in this type, replaced by a DDSand everything and OK.
Steph.
