### ISSUE TITLE
Mun terrain stones generate above surface

### ISSUE THREAD

**Issue by Alexsys** [Gameslinx/Tessellation#92]
ASTOUNDING what mod you've made!
im here witnessing history, I love you.

I've enabled just collision in the CFG, and all installed well.
performace is baby sweet and all.

The report here is over the rocks generating above ground, they have no collison to them (thankfully in this situation lmao)
so they look odd

Floating rocks basically :)

https://i.imgur.com/8qp2rOz.png

https://i.imgur.com/GxsmBk8.jpeg

**Comment by Gameslinx** [comment]
This will happen due to the scatter mesh and the terrain mesh. It was much easier for me to group rocks into single meshes instead of making each rock its own individual mesh. In hindsight, would have been better and avoided this from happening but a lot more effort. Nothing is actually wrong here, it's just a limitation of my implementation
